### PR TITLE
Add the ability to show likes when requesting all discussions

### PR DESCRIPTION
**Pull request by nielstholenaar**

### CODE REVIEW

**Comment by franzliedke** [comment]
Hmm, I'm not 100% sure we want to allow that, that could be quite a lot of records...

Can you explain the use case? (It would be nice if you could add descriptions to pull requests, in any case.)

**Comment by nielstholenaar** [comment]
My apologizes for not including an description. I thought the title was describing enough.

We the API of Flarum to show the discussions within our own dashboard. We would like to show total amount of likes of each start post. This changes allows us to do that.

**Comment by franzliedke** [comment]
Thanks! :)

As I said, I'm a little concerned about the possible server load implications of this. We could think about optionally exposing the _count_ of likes, though - as that's what you're interested in?

**Comment by nielstholenaar** [comment]
I do agree that returning all the details of each like, may have an performance impact. I'll try to modify the code to return only the total count of likes.

**Comment by franzliedke** [comment]
@nielstholenaar Have you made any progress with this?

**Comment by nielstholenaar** [comment]
@franzliedke No, we are currently moving away from flarum to a new CRM system which has a built-in forum / community part.

**Comment by tobyzerner** [comment]
Will close this then.

To achieve this we would need to add a `likes_count` column to the `posts` table, keep it up-to-date, and expose it in the JSON API. But not worth spending any time on right now, as ultimately the aim is to replace this extension with a more powerful/configurable "Reactions" extension.

**Pull request closed without merging**
