### PR TITLE
Prevent likes on locked discussion

### PR DESCRIPTION
**Pull request by KyrneDev**
This will truly "Lock" the discussion and won't allow dislikes and likes

### CODE REVIEW

**Comment by tobyzerner** [comment]
Hi @issyrocks12! Thanks for the PR - looks great!

However, this solution only gets us halfway there, because it only hides the like/unlike button on the frontend. Clever people would still be able to manually call the API to like/unlike posts in locked discussions.

In order to prevent this, we need to add a "PostPolicy" class to the likes extension, to specify that a user only has permission to like a post if the discussion which the post is in is not locked. It should be similar to [this](https://github.com/flarum/flarum-ext-lock/blob/master/src/Access/PostPolicy.php), but the method name should be `like` instead of `edit`.

Furthermore, your proposed JS code makes the likes extension depend on the lock extension – if the lock extension is disabled, then the code will crash (`isLocked` will not be a function). Luckily, this will be solved by adding the policy too, because the custom JS code will no longer be needed – the policy will be reflected automatically in `post.canLike()`.

If you don't understand or need some help, let us know :) Thanks for contributing!

**Comment by KyrneDev** [comment]
I've changed it to use `PostPolicy`, somehow I haven't seen this and I will be using this in my extensions in the future for sure, thanks for the tip!

Edit: Changed it to satisfy StyleCI but for some reason it wants to delete and add the same bracket.

**Comment by franzliedke** [comment]
Thanks for the changes, @issyrocks12. This is much better.

However, this still means that the Likes extension would depend on the Lock extension.

My proposal, but let's wait for @tobscure's comment: We should add another permission for generically **touching** posts: This would be checked whenever doing things to posts, such as editing, deleting or liking them, in addition to the more specific permissions that already exist. That way, the locks extension could simply disallow touching posts whenever the discussion is locked.

---

That said: What's the rationale behind disallowing likes / dislikes? Do we have a ticket or a discussion about this? That would e.g. disallow liking announcement posts in communities where these posts (general announcements) are locked immediately.

**Comment by KyrneDev** [comment]
Hey @franzliedke, thanks for the response!

This change will not make it depend on the lock extension, if it is not enabled (or if the discussion is not locked) is_locked will return null, allowing the like to be posted. 

There have been several requests to fully lock a discussion, we could potentially turn this into a setting.

**Comment by franzliedke** [comment]
@tobscure Can you weigh in here? What do you think about my proposal?

**Comment by tobyzerner** [comment]
@franzliedke I like your proposal :)

**Comment by franzliedke** [comment]
I'd like to re-raise this question:

> What's the rationale behind disallowing likes / dislikes? Do we have a ticket or a discussion about this? That would e.g. disallow liking announcement posts in communities where these posts (general announcements) are locked immediately.

**Comment by tobyzerner** [comment]
@franzliedke Yeah I'm not sure. Discourse seems to allow likes in locked topics, GitHub does not allow reactions in locked issues... I'd say GitHub is a bit of a different use-case though, and it makes sense for a forum (particularly in the general announcement scenario) to continue to allow them.

**Comment by franzliedke** [comment]
Indeed. Let's close this then.

Sorry for the long wait and thanks for improving upon the original PR, @CDK2020!

**Pull request closed without merging**
